# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "testing" do |vmHost1|
    vmHost1.vm.box = "ubuntu/jammy64"
    vmHost1.vm.hostname = "vmHost1"

    #_____________________________________________________________________________________________
    #vmHost1.vm.network "private_network", :name => '', ip: "192.168.56.5", virtualbox__intnet: true
    #vmHost1.vm.network "private_network", :name =>  '', ip: "192.168.56.5", virtualbox__intnet: true
    vmHost1.vm.network "private_network", ip: "192.168.56.5"
    vmHost1.vm.network "forwarded_port", guest: 8081, host: 18081, auto_correct: true
    
    # Comparto la carpeta del host donde estoy parado contra la vm
    vmHost1.vm.synced_folder 'compartido_Host1/', '/home/vagrant/compartido', 
    owner: 'vagrant', group: 'vagrant' 

      # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
      vmHost1.ssh.insert_key = true
      # Agrego un nuevo disco 
      vmHost1.vm.disk :disk, size: "5GB", name: "#{vmHost1.vm.hostname}_disk_vm1_1"
      vmHost1.vm.disk :disk, size: "3GB", name: "#{vmHost1.vm.hostname}_disk_vm1_2"
      vmHost1.vm.disk :disk, size: "2GB", name: "#{vmHost1.vm.hostname}_disk_vm1_3"
      vmHost1.vm.disk :disk, size: "1GB", name: "#{vmHost1.vm.hostname}_disk_extra_storage"

      vmHost1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "vmHost1"
        vb.cpus = 1
        vb.linked_clone = true
        # Seteo controladora Grafica
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']      
      end    
      # Puedo Ejecutar un script que esta en un archivo
      vmHost1.vm.provision "shell", path: "scripts/script_Enable_ssh_password.sh"
      vmHost1.vm.provision "shell", privileged: false, path: "scripts/script_Fix_history.sh"
      vmHost1.vm.provision "shell", path: "scripts/instala_paquetes.sh"
      #vmHost1.vm.provision "shell", path: "scripts/script_habilitar_x.sh"
      vmHost1.vm.provision "shell", privileged: false, inline: <<-SHELL
      # Los comandos aca se ejecutan como vagrant
  
      mkdir -p /home/vagrant/repogit
      cd /home/vagrant/repogit
      git clone https://github.com/lautaguardia29/TP_AySO_Integral_GGF.git

    SHELL
    end
    
    
    config.vm.define :produccion do |vmHost2|
      vmHost2.vm.box = "fedora/39-cloud-base"
      vmHost2.vm.hostname = "vmHost2"
      
      #vmHost2.vm.network "private_network", :name => '', ip: "192.168.56.6", virtualbox__intnet: true
      #vmHost2.vm.network "private_network", :name =>  '', ip: "192.168.56.6", virtualbox__intnet: true
      vmHost2.vm.network "private_network", ip: "192.168.56.6"
      vmHost2.vm.network "forwarded_port", guest: 8081, host: 18081, auto_correct: true
      
      # Comparto la carpeta del host donde estoy parado contra la vm
      vmHost2.vm.synced_folder 'compartido_Host2/', '/home/vagrant/compartido'

      # #Agrego nuevos discos
      # vmHost2.vm.disk :disk, size: "5GB", name: "#{vmHost2.vm.hostname}_disk_vm2_1"
      # vmHost2.vm.disk :disk, size: "3GB", name: "#{vmHost2.vm.hostname}_disk_vm2_2"
      # vmHost2.vm.disk :disk, size: "2GB", name: "#{vmHost2.vm.hostname}_disk_vm2_3"
      # vmHost2.vm.disk :disk, size: "1GB", name: "#{vmHost2.vm.hostname}_disk_vm2_extra_storage"
  
    # Agrega la key Privada de ssh en .vagrant/machines/default/virtualbox/private_key
    vmHost2.ssh.insert_key = true
    vmHost2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.name = "vmHost2"
      vb2.cpus = 1
      vb2.linked_clone = true
      # Seteo controladora Grafica
      vb2.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end
    
    # Puedo Ejecutar un script que esta en un archivo
    vmHost2.vm.provision "shell", path: "scripts/script_Enable_ssh_password.sh"
    vmHost2.vm.provision "shell", privileged: false, path: "scripts/script_Fix_history.sh"
    vmHost2.vm.provision "shell", path: "scripts/script_config_red_produccion.sh"

    # Provisión para instalar
    vmHost2.vm.provision "shell", inline: <<-SHELL
      dnf install -y tree
    SHELL
    
  end
end
