- name: "Alta_Usuarios_{{ grupo_nombre }} : Obtener el hash de la contraseña del usuario vagrant"
  ansible.builtin.shell: "grep '^vagrant:' /etc/shadow | cut -d: -f2"
  register: vagrant_password_hash_result
  delegate_to: "{{ inventory_hostname }}"
  changed_when: false

- name: "Alta_Usuarios_{{ grupo_nombre }} : Crear grupo secundario para el grupo"
  ansible.builtin.group:
    name: "{{ grupo_nombre }}"
    state: present

- name: "Alta_Usuarios_{{ grupo_nombre }} : Crear grupos principales G_R1 a G_R6"
  ansible.builtin.group:
    name: "G_{{ item.rol }}"
    state: present
  loop: "{{ integrantes }}"

- name: "Alta_Usuarios_{{ grupo_nombre }} : Crear usuarios y asignar grupos y contraseña"
  ansible.builtin.user:
    name: "{{ item.rol | lower }}_{{ item.nombre | lower }}"
    comment: "{{ item.nombre }} {{ item.apellido }} {{ item.descripcion_rol }}"
    create_home: yes
    group: "G_{{ item.rol }}"
    groups: "{{ grupo_nombre }}"
    password: "{{ vagrant_password_hash_result.stdout }}"
    state: present
    shell: /bin/bash
  loop: "{{ integrantes }}"
  loop_control:
    label: "Creando usuario {{ item.rol | lower }}_{{ item.nombre | lower }}"
