- name: Crear directorio /tmp/Grupo
  file:
    path: /tmp/Grupo
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'


- name: Crear archivo datos.txt con la info del grupo
  template:
    src: datos.txt.j2
    dest: /tmp/Grupo/datos.txt
    owner: vagrant
    group: vagrant
    mode: '0644'

